---
title: Homework 8 - World Bank Analysis
---

GITHUB URL:  <https://github.com/cmsc-vcu/cmsc408-sp2025-hw8-jleonard99>


# Problem Background


```{python}
from helpers import create_database_engine, run_sql_and_return_df, run_sql_and_return_html, create_db_wrapper, execute_ddl_from_file, execute_ddl

# Load these variables from .env file.
config_map = {
  'user': "CMSC408_HW8_USER",
  'password': "CMSC408_HW8_PASSWORD",
  'host': "CMSC408_HW8_HOST",
  'database': "CMSC408_HW8_DB_NAME"
}

cnx,config = create_db_wrapper( config_map )
  
```


```{python}
# Do a quick test of the connection and trap the errors better!

run_sql_and_return_html(cnx,"""
select
  table_schema, table_name, table_rows
from
  information_schema.tables
where
  table_schema in ('world_bank_data')
""")

```

# Exercises

In the following exercises, write the SQL as requested to discover the answer.

## Task 1

How many records are in the country table?

```{python}
# How many records are in the world_bank_data.wdi_country table?
# (skills: select, aggregate)

run_sql_and_return_html(cnx,"""
select
  count(*) as "Row Count"
from
  world_bank_data.wdi_country
""")

```

## Task 2

Explore the first 5 records in the country table.

```{python}
## write out the first 10 records and look at the columns
## Do you see any blanks or missing data?
## (skills: select, limit)

run_sql_and_return_html(cnx,"""
select
  *
from 
  world_bank_data.wdi_country
limit 5
""")

```


## Task 3

List all non-countries.

```{python}
## task 3
## Which records are NOT for countries, that is they're for regions or groups of countries.
## How can you tell?
## Once you figure it out, write a query to list all the non-countries
## (skills: select, where)

run_sql_and_return_df(cnx, """
select
    `Short Name`
from
    world_bank_data.wdi_country
where
    region = '' or region is null

""")
```

## Task 4

Create your own copy of WDI_Country containing just countries.

```{python}
## task 4
## The WDI table clearly contains information for countries and non-countries
## using CREATE TABLE ... SELECT from WHERE syntax.
## Finally, below write a query to return the number
## of records in the new table.
## (skills: select, aggregate)

# drop table
execute_ddl(cnx, """
drop table if exists wdi_country;
""")
```

```{python}
# create table
execute_ddl(cnx, """
create table wdi_country as
select * from world_bank_data.wdi_country
where region is not NULL
""")
```

```{python}
# show number of records
run_sql_and_return_df(cnx, """
select count(*) from wdi_country
""")
```

## Task 5

```{python}
## create local wdi data table using world_bank_data.wdi_data
## (skills: create table)

# drop table
execute_ddl(cnx, """
drop table if exists wdi_data;
""")
```

```{python}
run_sql_and_return_df(cnx, """
show tables;
""")
```

## Task 6

```{python}
## create local table of series table using world_bank_data.wdi_series
## The series table contains information
## about the data that you're using.
## (skills: create table)

# drop table
execute_ddl(cnx, """
drop table if exists wdi_series;
""")
```

```{python}
execute_ddl(cnx, """
create table wdi_series as
select * from world_bank_data.wdi_series;
""")
```

```{python}
run_sql_and_return_df(cnx, """
show tables;
""")
```

## Task 7

```{python}
## How many countries are in each region?
## (skills: select, aggregate, group by, order by)

run_sql_and_return_df(cnx,"""
select 
    region as "Region",
    count(*) as "Number of Countries"
from
    wdi_country
where 
    region is not null
group by
    region
order by
    "Number of Countries" desc;
""")

```

## Task 8

List the country full names and regions for all countries in north america.

```{python}
## List the country full names and regions for all countries in north america
## (skills: select, where, order by)

run_sql_and_return_df(cnx,"""
select
    `Long Name` as "Country Full Name",
    region as "Region"
from
    wdi_country
where
    region = 'North America'
order by
    `Long Name`;
""")

```

## Task 9

```{python}
## The last World Cup soccer tournament was hosted by Qatar.
## What region contains Qatar?  List the region, country short name and full name
## (skills: select, where)

run_sql_and_return_df(cnx,"""
select
    region as "Region",
    `Short Name` as "Country Short Name",
    `Long Name` as "Country Full Name"
from
    wdi_country
where
    `Short Name` = 'Qatar';
""")

```

## Task 10

```{python}
## There are two abbreviation fields in the data country_abbr and country_wb_abbr.
## List the country code, short name, abbr, wb_abbr and region for all the countries
## where the abbr and wb_abbr are different.
## (skills: select, where, order by)

run_sql_and_return_df(cnx,"""
select
    `Country Code` as "Country Code",
    `Short Name` as "Country Short Name",
    `2-alpha code` as "Abbreviation",
    `WB-2 code` as "World Bank Abbreviation",
    region as "Region"
from
    wdi_country
where
    `2-alpha code` <> `WB-2 code`
order by
    `Short Name`;
""")

```

## Task 11

```{python}
## Now, let's investigate the "income category" field.
## List the income categories and the number of countries in each
## income category in descending order of most countries to least.
## (skills: select, aggregate, group by, order by)

run_sql_and_return_df(cnx,"""
select
    `Income Group` as "Income Category",
    count(*) as "Number of Countries"
from
    wdi_country
group by
    `Income Group`
order by
    "Number of Countries" desc;
""")
```

## Task 12

```{python}
## Mystery task.  Looking at the table from Task 11 (anything odd?) write the
## next obvious query based on the results in the table.
## At a minimum, your query should put country short name in the first column.
## you will be scored on the number of records returned and the value(s) 
## in the first column.

run_sql_and_return_df(cnx,"""
select
    `Short Name` as "Country Short Name",
    `Income Group` as "Income Category",
    `WB-2 Code` as "WB-2 Code"
from
    wdi_country
where
    `Income Group` is NULL
order by
    `Short Name`;
""")

```

## Task 13

```{python}
## OK, this HAS to be an error. Let's make a assumption that the country 
## in question, because they are oil-rich, are "high income".  
## Write an update comment to correct the issue.
## NOTE - if you get this wrong, all subsequent tables will be wrong!

execute_ddl(cnx,"""
update
    wdi_country
set 
    `Income Group` = "High Income"
where
    `Short Name` = "Venezuela"; 
commit;
""")
```


```{python}
## Now, display the country again to verify the change stuck!

run_sql_and_return_df(cnx,"""
select
    `Short Name` as "Country Short Name",
    region,
    `Income Group` as "Income Category"
from
    wdi_country
where
    `Short Name` = "Venezuela";
""")
```

## Task 14

```{python}
## Write a single query that show the number of countries in each 
## "Region"-"Income Group" pair.  The table should have 3 columns:
## region, income group, and no.of.countries.
## (skills: select, aggregate, group by, order by)

run_sql_and_return_df(cnx,"""
select
    region as "Region",
    `Income Group` as "Income Category",
    count(*) as "Number of Countries"
from
    wdi_country
group by
    region, `Income Group`
""")

```

## Task 15

```{python}
## Examine the result from task 14. It would be really cool to
## present the results of this table in a 2-D form, with 
## columns for each income category (high, upper middle, lower middle, low, other)
## regions down the side, and the pair-wise count inside each cell.
## Using CASE statements, DO IT!  BE SURE to include the countries without
## an income category.

## HINT - your query should return 6 columns: the region name, one
## column for each of the income categories (e.g., High, Upper middle, etc.)
## and a column for the row totals.
## (skills: select, aggregate, group by, nested query)

run_sql_and_return_df(cnx,"""
select
    region as "Region",
    sum(case when `Income Group` = 'High income' then 1 else 0 end) as "High Income",
    sum(case when `Income Group` = 'Upper middle income' then 1 else 0 end) as "Upper Middle Income",
    sum(case when `Income Group` = 'Lower middle income' then 1 else 0 end) as "Lower Middle Income",
    sum(case when `Income Group` = 'Low income' then 1 else 0 end) as "Low Income",
    cast(count(*) as decimal(10,1)) as "Row Total"
from
    wdi_country
group by
    region
""")

```

## Task 16

```{python}
## Wow! what a cool table!  It is very interesting to see where the money
## sits around the world.  Using the general approach from Task 14 above
## and write a query to return the single region with the most lower-income
## countries.

## Your query should return 3 columns, the number of 
## low-income countries, the region name and the income group

## PUT THE NUMBER FIRST! (use: count, region name, income group)
## (skills: select, aggregate, group by, nested query, order by, limit)

run_sql_and_return_df(cnx,"""
select
    count(*) as "Number of Low-Income Countries",
    region as "Region"
from
    wdi_country
where
    `Income Group` = 'Low income'
group by
    region
""")
```

## Task 17

```{python}
## Are you getting the hand of this? Good! We need to take a look at all
## the countries in the same region and with the same income category as
## the Marshall Islands.
## For each country that matches, print their country code, short name,
## region and income category, by order of their short name.  As a hint,
## the country code for the Marshall Islands is MHL.
## (skills: select, where, subquery)

run_sql_and_return_df(cnx,"""
select
    `Country Code` as "Country Code",
    `Short Name` as "Country Short Name",
    region as "Region",
    `Income Group` as "Income Category"
from
    wdi_country
where
    region = (select region from wdi_country where `Country Code` = 'MHL')
    and `Income Group` = (select `Income Group` from wdi_country where `Country Code` = 'MHL')
""")

```

## Task 18

```{python}
## OK - let's raise the heat in the kitchen! Review the output from task 14.
## You'll see that some of the regions do not contain all of the income
## levels.  For example, the Europe & Central Asia region does not have
## any low income countries.
##
## CHALLENGE - using a SINGLE SQL statement, write a table that contains every
## combination of region and income category (including the missing '') values!
##
## THEN add a WHERE clause to only show the values that were missing from
## the original pairings!
##
## HINT - there should be AT MOST [# of regions]x[# of income cats] = 28
## rows in your final table, and there are 22 rows returned in the query
## in Task 14.  (FYI - I get 6 rows in my final table.)
## (skills: select, where, subqueries, joins)

run_sql_and_return_df(cnx,"""
select 
  r.region as "Region",
  i.`Income Group` as "Income Group",
  count(c.`Short Name`) as "Number of Countries"
from 
  (select distinct region from wdi_country) r
cross join 
  (select distinct `Income Group` from wdi_country) i
left join 
  wdi_country c
on 
  r.region = c.region and i.`Income Group` = c.`Income Group`
group by 
  r.region, i.`Income Group`
having 
  count(c.`Short Name`) = 0
order by 
  r.region, i.`Income Group`;
""")

```

## Task 19

```{python}
## Hot enough, yet?  Let's go for ghost-pepper HOT!  Now let's build some
## percentage tables.  For example, across the entire sample, what
## is the percentage of total countries in each income category?
##
## As a first step, build off the result from task 14 and create a table with
## six columns (region, income cat, country count, sum of countries in region,
## sum of countries by income and total sum countries).
##
## THEN, add a 7th column calculating the percent of total for each,
## region-income pair.
##
## actually calculating percentages and print out a table will be a
## slam dunk after this!
## (skills: select, where, subqueries, joins, aggregate functions)

run_sql_and_return_df(cnx,"""
with region_cte as (
    select region, count(*) as region_cnt 
    from wdi_country 
    group by region
), income_cte as (
    select `Income Group`, count(*) as income_cnt 
    from wdi_country 
    group by `Income Group`
), total_cte as (
    select count(*) as total_cnt 
    from wdi_country
), pair_cte as (
    select 
        region,
        `Income Group`,
        count(*) as pair_cnt
    from 
        wdi_country
    group by 
        region, 
        `Income Group`
), merge_cte as (
    select 
        a.region,
        a.`Income Group`,
        pair_cnt,
        region_cnt,
        income_cnt,
        total_cnt,
        round(100.0 * pair_cnt / total_cnt, 1) as "Pct of Total"
    from 
        pair_cte a
        left join region_cte b on (a.region = b.region)
        left join income_cte c on (a.`Income Group` = c.`Income Group`),
        total_cte d
)
select * from merge_cte
""")


```

## Task 20

```{python}
## SLAM DUNK TIME!  Using the resulting table CTEs from Task 19,
## print table similar to the table in Task 15, with Income group in the
## columns, Region in the rows and Percent of total in each cell of the table.

run_sql_and_return_df(cnx,"""
with region_cte as (
    select region, count(*) as region_cnt 
    from wdi_country 
    group by region
), income_cte as (
    select `Income Group`, count(*) as income_cnt 
    from wdi_country 
    group by `Income Group`
), total_cte as (
    select count(*) as total_cnt 
    from wdi_country
), pair_cte as (
    select 
        region,
        `Income Group`,
        count(*) as pair_cnt
    from 
        wdi_country
    group by 
        region, 
        `Income Group`
), merge_cte as (
    select 
        a.region,
        a.`Income Group`,
        pair_cnt,
        region_cnt,
        income_cnt,
        total_cnt,
        100.0 * pair_cnt / total_cnt as pct
    from 
        pair_cte a
        left join region_cte b on (a.region = b.region)
        left join income_cte c on (a.`Income Group` = c.`Income Group`),
        total_cte d
)
select 
    region,
    round(sum(case when `Income Group` = 'Low income' then pct else 0 end), 1) as "Low Income",
    round(sum(case when `Income Group` = 'Lower middle income' then pct else 0 end), 1) as "Lower Middle Income",
    round(sum(case when `Income Group` = 'Upper middle income' then pct else 0 end), 1) as "Upper Middle Income",
    round(sum(case when `Income Group` = 'High income' then pct else 0 end), 1) as "High Income",
    round(sum(pct), 1) as "Row Total"
from 
    merge_cte
group by 
    region;
""")

```

## Task 21

```{python}
## ANOTHER DUNK!  Using the resulting table CTEs from Task 19,
## print a table listing the number, totals and percentage of countries
## by income category.

## (This is much simpler than task 20!)

run_sql_and_return_df(cnx,"""
select
    `Income Group` as "Income Category",
    count(*) as "Number of Countries",
    (select count(*) from wdi_country) as "Total Count",
    round(count(*) * 100.0 / (select count(*) from wdi_country), 1) as "Percent of Total"
from
    wdi_country
group by
    `Income Group`
order by
    "Income Category";
""")

```


# Reflection

1. Reflect on the SQL skills you used throughout these exercises. Which skills do you feel most confident in, and which do you think need more practice? How has this assignment helped you build or reinforce specific SQL competencies?

( response goes here)

2. Problem-Solving Approach: Describe your approach to tackling the more complex tasks (like Tasks 18, 23, and 24). How did you break down these problems, and what steps did you take when you encountered challenges? How would you approach a similar problem differently in the future?

( response goes here)


3. Learning Takeaways: Consider the overall learning experience from this assignment. What were the biggest takeaways about working with SQL for data analysis and transformation? How do you think these skills will apply in real-world scenarios or future coursework?

( response goes here)


# README

A quality README is an important part of EVERY project. Using the Quarto *include* command we're including a copy of your README in the project report so that a human can evaluate it.

Make sure that you edit the README so that it's explanatory!  Note that you don't need a readme within the *reports* folder for this assignment. We're only
focused on the root *README.md*.

[Here is some info](https://www.freecodecamp.org/news/how-to-write-a-good-readme-file/) on how to write a good README!

::: {style="background:lightgray; margin-left:20px; border-top: 3px solid black; border-bottom: 3px solid black; padding-left:20px; padding-right:20px"}
{{< include ../README.md >}}
:::

